theonion/bulbs-elements

elements/bulbs-poll/bulbs-poll.test.js
karma.base.js
scripts/develop-and-test
webpack.config.dev.js

karma-webpack test runner

---

lib/bulbs-elements/store/store.js

@kand @collin This error is preventing me from cutting a release candidate

Fix lint errors on constant condition

---

package.json
scripts/tag-and-release

Honest documentation

---

lib/bulbs-elements/util/make-request.js
lib/bulbs-elements/util/make-request.test.js
package.json

@kand @collin Just adding some tests for makeRequest.

Backfill tests

---

scripts/tag-and-release

@collin We need to enforce master branch for release

Force master release branch

---

elements/campaign-display/campaign-display-schema.js
elements/campaign-display/campaign-display.js
elements/campaign-display/components/campaign-display-image.js
elements/campaign-display/components/campaign-display-image.test.js
elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js
elements/campaign-display/fields/campaign-field.js
elements/campaign-display/fields/campaign-field.test.js
elements/campaign-display/fields/campaign-request-field.js
elements/campaign-display/fields/campaign-request-field.test.js

@kand @collin I need some eyes on this. The tests pass but I want to make sure I understand all the plumbing.

Refactor request implementation

---

elements/campaign-display/components/campaign-display-image.js
elements/campaign-display/components/campaign-display-image.test.js

Don't wrap the campaign image when there is no campaign url

---

elements/campaign-display/campaign-display-examples.js
elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/fields/campaign-field.js
elements/campaign-display/fields/campaign-field.test.js
elements/campaign-display/fields/campaign-request-field.js
elements/campaign-display/fields/campaign-request-field.test.js
examples/fixtures/campaign-display/campaign.json

@kand @collin This adds examples and actually works

Campaign display examples

---

elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js

Handle missing campaign response

---

elements/campaign-display/campaign-display-examples.js
elements/campaign-display/campaign-display.js
elements/campaign-display/campaign-display.test.js
elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js
examples/fixtures/campaign-display/missing-campaign.json
lib/bulbs-elements/util/make-request.js

I took a more thorough pass at handling missing data.
@kand @collin

Gracefully handle empty data

---

elements/campaign-display/components/dfp-pixel.test.js
elements/campaign-display/components/logo.js
elements/campaign-display/components/logo.test.js
elements/campaign-display/components/sponsor-name.js

Sweet console stubbing voodoo action

---

elements/campaign-display/campaign-display.js

Fix incorrect property name

---

README.md
elements/campaign-display/components/logo.js
elements/campaign-display/components/logo.test.js
lib/bulbs-elements/components/cropped-image.js
lib/bulbs-elements/components/cropped-image.test.js

I had a need for `<CroppedImage/>` in `<bulbs-video>`. So I hoisted it out here.
@kand @daytonn

Cropped image

---

elements/campaign-display/campaign-display.js
elements/campaign-display/campaign-display.scss
elements/campaign-display/campaign-display.test.js
elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js

Add logo crop property to campaign-display

---

elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js

Implement awareness of changes in https://github.com/theonion/tunic/pull/50.

<campaign-display> Add check for active campaign

---

elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js

Added handling of missing preamble text, and missing campaign id

Handle all cases of missing information

---

elements/campaign-display/campaign-display.js
elements/campaign-display/campaign-display.test.js
elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js
elements/campaign-display/components/logo.js
elements/campaign-display/components/logo.test.js

Remove cropped image from campaign-display

---

elements/campaign-display/components/sponsor-name.js
elements/campaign-display/components/sponsor-name.test.js

Change default to expect a boolean for noLink on sponsor name

---

elements/campaign-display/campaign-display.js
elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js
elements/campaign-display/components/logo.js
elements/campaign-display/components/logo.test.js
elements/campaign-display/components/sponsor-name.js
elements/campaign-display/components/sponsor-name.test.js

Added some enzyme testing refactors too ;)
@kand @collin

Wrap all campaign-display components in a link to the clickthrough_url

---

.eslintrc
elements/bulbs-poll/components/request-error.js
elements/campaign-display/campaign-display.js
elements/campaign-display/campaign-display.test.js
elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js
elements/campaign-display/components/dfp-pixel.test.js
examples/component.js
examples/examples.js
examples/index.js
package.json

Clean up lint errors and warnings

---

elements/campaign-display/components/campaign-display-root.js
elements/campaign-display/components/campaign-display-root.test.js

Check for valid active campaign before rendering

---

elements/share-tools/README.md
elements/share-tools/components/root.js
elements/share-tools/components/root.test.js
elements/share-tools/components/share-button.js
elements/share-tools/components/share-button.test.js
elements/share-tools/components/share-tool.js
elements/share-tools/components/share-tool.test.js
elements/share-tools/components/via-email.js
elements/share-tools/components/via-email.test.js
elements/share-tools/components/via-facebook.js
elements/share-tools/components/via-facebook.test.js
elements/share-tools/components/via-twitter.js
elements/share-tools/components/via-twitter.test.js
elements/share-tools/share-tools-examples.js
elements/share-tools/share-tools.js
elements/share-tools/share-tools.scss
elements/share-tools/share-tools.test.js

Look ma, `<share-tools>`
These need some documentation love.

share tools

---

.gitignore
package.json
scripts/webpack-build-stats
webpack.base.js

Starting to optimize output based on information from stats.

optimize chunks

---

elements/bulbs-carousel/bulbs-carousel-state.js
elements/bulbs-carousel/bulbs-carousel.js
elements/bulbs-carousel/item.js
elements/bulbs-video/bulbs-video-meta-examples.js
elements/bulbs-video/bulbs-video.js
elements/bulbs-video/components/revealed.js
elements/bulbs-video/elements/meta.js
elements/bulbs-video/elements/meta.test.js
elements/bulbs-video/elements/summary.js
elements/bulbs-video/elements/summary.scss
elements/bulbs-video/elements/summary.test.js
elements/bulbs-video/elements/video-carousel.js
elements/bulbs-video/elements/video-carousel.test.js
package.json

This builds on the `<bulbs-carousel>` `<bulbs-video-carousel>` refactor to support the design for the homepage video players.
@spra85 @kand @daytonn @MelizzaP

homepage player components

---

elements/bulbs-slideshow/bulbs-slideshow.test.js
elements/campaign-display/components/dfp-pixel.test.js
karma.base.js

Hey @daytonn looks like only the coverage is broken here.
I'm going to merge this into master as it's blocking the homepage player. Thanks! :)

Fix broken build

---

elements/bulbs-video/elements/video-carousel.js

@daytonn @kand can you take a look at this?

fix error in updating sharetools share-title

---

elements/bulbs-clickventure/clickventure.js

This was causing page tracking not to fire.

Remove broken conditional

---

elements/bulbs-video/elements/rail-player/components/campaign.js
elements/bulbs-video/elements/rail-player/components/campaign.test.js

@MelizzaP @spra85 @daytonn @kand @shawncook @jmelvnsn 
Overlooked this in the rail-player.

campaign in rail player is name-only

---

elements/bulbs-video/elements/meta/components/root.test.js
elements/bulbs-video/elements/rail-player/components/root.js
elements/bulbs-video/elements/rail-player/components/root.test.js

update rail player targeting

---

elements/bulbs-carousel/bulbs-carousel.scss
lib/bulbs-elements/components/video-play-button.js
lib/bulbs-elements/components/video-play-button.scss

@spra85 @collin Fixes unstyled share buttons on carousel items

Make styles available to carousel play button

---

elements/bulbs-video/components/revealed.js
elements/bulbs-video/components/revealed.test.js
package.json

@spra85 I think this matches our notes from last night.
@kand @daytonn Pulled in a url parser for saner url testing ;)

construct vastUrl `s` rather than passing category thru

---

elements/share-tools/README.md
elements/share-tools/components/share-tool.js
elements/share-tools/components/share-tool.test.js
elements/share-tools/components/via-disqus.js
elements/share-tools/components/via-disqus.test.js

@jmelvnsn @shawncook @MelizzaP @spra85 @daytonn @kand

default to current url for share url

---

elements/clickhole-medal-tracker/components/contender.js

adding some markup around this data

---

elements/clickhole-medal-tracker/components/contenders.js
elements/share-tools/components/via-email.js
elements/share-tools/components/via-email.test.js

replaces mailto click handler w/href

---

elements/notification-container/notification-display.js

hey @benghaziboy @kand @collin is this a kosher change?

clicktracking for notifications

---

elements/notification-container/notification-display.js

this is a really sad error i made

Clicktracking

---

elements/notification-container/notification-container.js
elements/notification-container/notification-container.test.js
elements/notification-container/notification-display.js

@kand @collin 
- Needed a wrapper for styling on avclub & onion.
- Need a way to pass in the content for the close box.

pass closeContent in

---

elements/share-tools/components/via-email.js
elements/share-tools/share-tools.js
package.json

Force attribute change on share-via-email

---

.gitignore
elements/bulbs-flyover-menu/bulbs-flyover-menu-examples.js
elements/bulbs-flyover-menu/bulbs-flyover-menu.js
elements/bulbs-flyover-menu/bulbs-flyover-menu.scss
elements/bulbs-flyover-menu/bulbs-flyover-menu.test.js
examples/index.html

To be used as such:
```html
<button is="bulbs-flyover-open" menu-name="example-menu">Open Menu</button>                                       
<bulbs-flyover-menu menu-name="example-menu">          
<button is="bulbs-flyover-close" menu-name="example-menu">Close Menu</button>                                     
<nav><a href="#">Get Yer Hot Links Here!</a></nav>
</bulbs-flyover-menu>                           
```
used in: http://www.avclub.com/the-mobo-movement

a flyover menu

---

elements/bulbs-poll/components/answer.js
elements/bulbs-poll/components/answer.test.js
elements/bulbs-poll/components/vote-button.js
elements/bulbs-poll/components/vote-button.test.js

@daytonn @shawncook 
Answer selection was breaking because of a function binding issue.
Guessing this changed between React 14 and 15?
@shawncook, try out this tag for `bulbs-elements` in `bower.json`:
```json
"bulbs-elements": "theonion/bulbs-elements#temp-a69fa10-fix-poll-answer-selection",
```

bind selectAnswer to  and make test more specific

---

elements/bulbs-video/components/revealed.js
elements/bulbs-video/elements/rail-player/components/campaign.js
elements/bulbs-video/elements/rail-player/components/campaign.test.js
elements/bulbs-video/elements/rail-player/components/root.js
elements/bulbs-video/elements/rail-player/components/root.test.js
elements/bulbs-video/elements/rail-player/rail-player.js
lib/bulbs-elements/util/get-analytics-manager.js
lib/bulbs-elements/util/index.js

@collin still need to add tests

rMVP analytics

---

elements/bulbs-video/bulbs-video.js
elements/bulbs-video/components/cover.js
elements/bulbs-video/components/cover.test.js
elements/bulbs-video/components/root.js
elements/bulbs-video/components/root.test.js

make meta cover hidden by default

---

elements/bulbs-clickventure/clickventure.js

reload ads every 5th node

---

elements/bulbs-video/bulbs-video.js
elements/bulbs-video/bulbs-video.scss
elements/bulbs-video/components/cover.js
elements/bulbs-video/components/cover.test.js
elements/bulbs-video/components/root.js
elements/bulbs-video/components/root.test.js
elements/bulbs-video/elements/meta/components/root.js
elements/bulbs-video/elements/meta/meta.js
elements/bulbs-video/elements/meta/meta.test.js

Inline video fixes

---

elements/bulbs-content/bulbs-content.js
elements/bulbs-content/bulbs-content.scss
elements/bulbs-content/bulbs-content.test.js

bulbs-content

---

elements/bulbs-ellipsize/README.md
elements/bulbs-ellipsize/bulbs-ellipsize-example.js
elements/bulbs-ellipsize/bulbs-ellipsize.js
elements/bulbs-ellipsize/bulbs-ellipsize.test.js
elements/bulbs-video/elements/meta/components/root.js
elements/bulbs-video/elements/meta/components/root.test.js
elements/bulbs-video/elements/meta/meta.js
elements/bulbs-video/elements/summary.js
elements/bulbs-video/elements/summary.test.js
elements/bulbs-video/elements/video-carousel.js
elements/bulbs-video/elements/video-carousel.test.js
package.json

truncates text, implemented in the homepage and special coverage players

Bulbs Ellipsize

---

elements/bulbs-video/elements/rail-player/rail-player.scss

one more style tweak

---

elements/bulbs-video/components/revealed.js

test link: **http://jw-player-test.test.theonion.com/interactive/american-voter**

append prefix to jw-player element id

---

elements/bulbs-poll/bulbs-poll.js
elements/bulbs-poll/bulbs-poll.test.js
elements/bulbs-video/bulbs-video.test.js
elements/bulbs-video/elements/rail-player/rail-player.test.js
karma.devicelab.js

These tests were breaking in weird ways in IE.

fixe some tests that don't pass in IE

---

elements/bulbs-reading-list/lib/reading-list-article.js
elements/bulbs-reading-list/lib/reading-list-article.test.js
elements/bulbs-reading-list/lib/reading-list-articles.js
elements/bulbs-reading-list/lib/reading-list-articles.test.js

update reading list menu behavior to load an article and then scroll to the article instead of redirecting to a new page

Reading List -- Menu Scroll behavior

---

elements/bulbs-reading-list/lib/reading-list-menu.js

test link: http://clickhole-rl-qa.test.clickhole.com/article/6-pieces-meat-i-have-seen-held-and-one-case-gone-v-4972

fix dissapearing menu behavior in chrome

---

elements/bulbs-video/components/revealed.js
elements/bulbs-video/components/revealed.test.js
elements/bulbs-video/components/root.js
elements/bulbs-video/elements/video-carousel.js

Update revealed.js to include shreUrl as an attribute of bulbs-video

---

elements/bulbs-liveblog/bulbs-liveblog-entry.js
elements/bulbs-reading-list/lib/reading-list-article.js

Updates to reading list code for implementation in onion.
Removes functionality that sites may be using.
1. Reading list no longer manages taboola, this is now a site specific responsibility.

remove taboola from reading list code

---

elements/bulbs-reading-list/lib/reading-list-article.js
elements/bulbs-reading-list/lib/reading-list-articles.js

Needed this to load disqus attributes for avclub reading list.

setting currentArticle on new reading list item active item

---

elements/bulbs-video/components/revealed.js
elements/bulbs-video/components/revealed.test.js

@spra85 I think I got the negation correct for the line in question, but would like your blessing.
@kand @collin

add disableAds prop to revealed.js & test

---

README.md

fix readme images

---

elements/bulbs-pollzone-map/bulbs-pollzone-map.js

travis wasn't catching this before but is now for some reason

pollzone lint fix

---

elements/bulbs-article-body/README.md
elements/bulbs-article-body/bulbs-article-body-examples.js
elements/bulbs-article-body/bulbs-article-body.js
elements/bulbs-article-body/bulbs-article-body.test.js

New element to apply things to an article body. Need this initially for appending dingbats, but it could be used for other things common to all articles.

bulbs-article-body

---

elements/bulbs-article-body/bulbs-article-body.js
elements/bulbs-article-body/bulbs-article-body.test.js

@theonion/front-end ready for review

resize iframes in <bulbs-article-body>

---

elements/bulbs-article-body/bulbs-article-body.js
elements/bulbs-article-body/bulbs-article-body.test.js

I was seeing multiple dingbat insertions on clickhole.
This seems like a good defense.

don't add a second dingbat to bulbs-article-body

---

elements/bulbs-reading-list/bulbs-reading-list.js
elements/bulbs-reading-list/components/bulbs-reading-list-menu-item-clickable-area.js
elements/bulbs-reading-list/components/bulbs-reading-list-menu-item-clickable-area.scss

Fixes a few issues released in https://github.com/theonion/bulbs-elements/pull/246.

some fixes for reading list menu precision

---

elements/bulbs-article-body/bulbs-article-body.js
elements/bulbs-article-body/bulbs-article-body.test.js

Resizing iframes seems like a fairly safe thing to do cross-domain.
@theonion/front-end

dont check iframe resizer origin

---

elements/bulbs-reading-list/lib/reading-list-menu.js

This is breaking with our changes that remove the existing sidebar from the reading list.
@mparent61

don't break if first item is missing

---

elements/bulbs-video/elements/rail-player/components/root.js
elements/bulbs-video/elements/rail-player/components/root.test.js
elements/bulbs-video/elements/rail-player/rail-player.js
elements/bulbs-video/elements/rail-player/rail-player.test.js

pass & test

---

elements/bulbs-truncate-element/bulbs-truncate-element.js
elements/bulbs-video/elements/video-carousel.js

don't need this call

---

lib/bulbs-elements/util/detect-ad-block.js

[The Asset In Question](http://assets2.onionstatic.com/onion/static/images/ad-block-check.jpg)

Switch to Akamai CDN static assets

---

elements/bulbs-liveblog/bulbs-liveblog-responses.js
elements/bulbs-liveblog/bulbs-liveblog.js

Updates for live blog.
Only contains fixes.
1. Remove new response button then check if response html has any content. If not, no new response button will be added.

liveblog iteration 3, phase 1

---

elements/bulbs-page/bulbs-page.js
elements/bulbs-page/bulbs-page.test.js

@spra85 @brycedorn 
https://github.com/theonion/omni/pull/1032
http://multi-entry-analytics.test.theonion.com/live/president-donald-trump-first-100-days-55086

Multi entry analytics setup

---

elements/bulbs-reading-list/lib/reading-list-article.js

All of the info captured in the `omni` repo PR here: https://github.com/theonion/omni/pull/1043

Update to the Reading List Scroll logic

---

elements/bulbs-video/player-skin-overrides.scss
package.json

the volume slider is still being wonky

rail player volume fix

---

elements/bulbs-pdfobject/bulbs-pdfobject.js

Add CTA Mobile button

---

elements/bulbs-dfp/bulbs-dfp.js

Patch for async load issue

---

elements/bulbs-video/elements/video-carousel.js
elements/bulbs-video/elements/video-carousel.test.js

Here is the other half of the PR for playing video carousel items based on the url routing.
https://github.com/theonion/omni/pull/1196

Video carousel routing

---

elements/bulbs-dfp/bulbs-dfp.js
elements/bulbs-slick-slideshow/bulbs-slick-slideshow.js

More details in Omni PR here (https://github.com/theonion/omni/pull/1244)

Slideshow monetization

---

elements/bulbs-reading-list/components/bulbs-reading-list-item.js
elements/bulbs-reading-list/components/bulbs-reading-list-item.test.js
elements/bulbs-video/components/revealed.test.js
elements/bulbs-video/elements/rail-player/rail-player.js
lib/bulbs-elements/util/detect-ad-block.js
lib/bulbs-elements/util/index.js
lib/bulbs-elements/util/prep-ga-wrapper.js
lib/bulbs-elements/util/prep-reading-list-analytics.js

Relevant, related PR (https://github.com/theonion/omni/pull/1197)

Includes ad-block detection lib inside of reading list custom components

---

lib/bulbs-elements/util/detect-ad-block.js

Relevant PR with more info in the integrating branch: https://github.com/theonion/omni/pull/1289

Use different ad block detection, if available

---

elements/bulbs-clickventure/bulbs-clickventure.js
elements/bulbs-quiz/bulbs-quiz.js
lib/bulbs-elements/util/index.js
lib/bulbs-elements/util/resize-parent-frame.js

Used for Clickhole migration to Kinja.
Leverages Kinja Mantle's built-in support for passing resize messages from within an embed iframe.

Quiz and Clickventure embeds resize (Kinja) parent frame

---

elements/bulbs-datamap/bulbs-datamap.js
package-lock.json
package.json

This fixes error with d3 pulling in outdated contextify lib that was breaking `npm install` with Node version >= 7

Updating d3.js

---

elements/bulbs-clickventure/bulbs-clickventure.js
elements/bulbs-clickventure/clickventure.js

[Asana Task](https://app.asana.com/0/464944410244520/627545553224569)
Clickventure analytics fixes:

More embed analytics fixes
