package.json
This is common for npm packages. Even though we have a convention of using scripts, we can still leverage npm to maintain the [principal of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).
=> Add test scripts for convenience and to maintain idiomatic npm project configuration

elements/campaign-display/fields/campaign-field.js, elements/campaign-display/fields/campaign-field.test.js, elements/campaign-display/fields/campaign-request-field.js, elements/campaign-display/fields/campaign-request-field.test.js, lib/bulbs-elements/store/store.js
Hack for displaying campaign data properly when using separate fields for request v. data.
**Note**: Remove this once we fix the way `store.js` works.
=> Campaign display fixes

elements/campaign-display/components/dfp-pixel.js, elements/campaign-display/components/dfp-pixel.test.js
Provides a `componentDidMount` hook for external libraries that need to interact with `<DfpPixel>` components when they're done rendering.
This takes `window.BULBS_ELEMENTS_ADS_MANAGER` and calls `reloadAds` from that. Requires that the correct `AdsManager` has been set to that variable, and the `AdsManager` interface has a `reloadAds(element)` function.
=> <campaign-display> <DfpPixel> with render even calling a window configuration

elements/campaign-display/components/campaign-display-root.js, elements/campaign-display/components/campaign-display-root.test.js
I forgot to check for content before rendering the preamble text
@kand @collin
=> Don't render preamble text if there is no logo or sponsor name

elements/campaign-display/components/dfp-pixel.js, elements/campaign-display/components/dfp-pixel.test.js, scripts/test-js
=> DfpPixel add dfp class and change ad manager call

elements/campaign-display/fields/campaign-field.js, elements/campaign-display/fields/campaign-field.test.js
Having an initial state with a blank name is causing some problems with rendering `DfpPixel`.
=> No init state for campaign field

elements/campaign-display/components/campaign-display-root.js, elements/campaign-display/components/campaign-display-root.test.js
Instead of rendering an empty string, we are now falling back to the SponsorName component
@kand @collin
=> Fallback to sponsor name if logo is missing

.eslintrc, elements/campaign-display/campaign-display.test.js, elements/campaign-display/components/campaign-display-root.js, elements/campaign-display/components/campaign-display-root.test.js, elements/campaign-display/components/logo.js, elements/campaign-display/components/logo.test.js, elements/campaign-display/components/sponsor-name.js, elements/campaign-display/components/sponsor-name.test.js
Added the ability to prevent the component from wrapping the components in a link to the `clickthrough_url`.
@kand @collin
=> Add noLink attribute to avoid double link wrapping

elements/campaign-display/campaign-display.js, elements/campaign-display/campaign-display.test.js, elements/campaign-display/components/campaign-display-root.js, elements/campaign-display/components/campaign-display-root.test.js, elements/campaign-display/components/logo.js, elements/campaign-display/components/logo.test.js
I noticed that if an image is missing, 2 sponsor names will display. We only want to fallback to the sponsor name if we asked for only an image and we didn't get one.
@kand @collin
=> Fix double sponsor name bug

elements/campaign-display/components/campaign-display-root.js, elements/campaign-display/components/campaign-display-root.test.js, lib/bulbs-elements/util/make-request.test.js
The tests I changed need to be converted to enzyme so the `props.children.props.children` madness is removed but right now I'm just trying not to have to revert the clickhole deploy.
@kand @collin @spra85
=> Add inner div wrapper to campaign-display

elements/campaign-display/components/campaign-display-root.js, elements/campaign-display/components/campaign-display-root.test.js
I noticed after the last patch that I was getting a bunch of errors in the console because I was no longer checking for a valid campaign before attempting to use it's properties.
@kand @collin
=> Prevent accessing properties on undefined keys

bower.json
@kand @collin 
Picks up video sharetools FB fix: https://github.com/theonion/videohub-player/commit/26712cdd7178b9e10adf135a8b718fc4f673faae
=> Bump videohub-player 1.0.1 (sharetools fix)

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js
@collin @daytonn @MelizzaP @kand ... Making this a passed in parameter instead of being based on the `global.targeting` value because it will vary based on placement.  This mirrors more closely the old functionality where the player was an iframe embed with a `?target_host_channel=special_coverage_main` query string param
=> Made host channel targeting a passed in parameter

elements/bulbs-video/bulbs-video-examples.js, elements/bulbs-video/bulbs-video.js, elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js, elements/bulbs-video/components/root.js
@collin @kand @daytonn @MelizzaP - if you could review, passes through `muted` attribute to the options for the video hub player used here: 
https://github.com/theonion/videohub-player/blob/master/src/player.js#L68
=> Allow muted attribute for bulbs-video element

.eslintignore, elements/bulbs-video/components/revealed.test.js, elements/bulbs-video/plugins/comscore.js, elements/bulbs-video/plugins/comscore.test.js, elements/bulbs-video/plugins/google-analytics.js, elements/bulbs-video/plugins/google-analytics.test.js, package.json
I ignored the big jwplayer/streamsense files and ran lint with `--fix` to cleanup the simple things.
Leaves us with this remaning:
```bash
monorepo/bulbs-elements/elements/bulbs-video/components/revealed.js
154:3  warning  Expected to return a value at the end of this method  consistent-return
monorepo/bulbs-elements/elements/bulbs-video/components/revealed.test.js
141:1   warning  Line 141 exceeds the maximum line length of 121  max-len
144:1   warning  Line 144 exceeds the maximum line length of 121  max-len
145:1   warning  Line 145 exceeds the maximum line length of 121  max-len
362:42  warning  Unexpected use of undefined                      no-undefined
369:42  warning  Unexpected use of undefined                      no-undefined
415:1   warning  Line 415 exceeds the maximum line …
```
=> jw player lint

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js, elements/bulbs-video/plugins/google-analytics.js, elements/bulbs-video/plugins/google-analytics.test.js
@collin @daytonn @kand @MelizzaP ... Will quiet some of the noise with the `aderror` and `adskipped` event logging
=> Filtering out the cachebuster param so the analytics are a bit easier to grok

elements/bulbs-splitpic/splitpic.js
This fixes split pics from starting at the default percentage when a custom percentage was given.
=> Fix start percentage reference

elements/bulbs-quiz/test-quiz.js
Fixes outcome totaling for test quiz type. jquery's `serializeArray` will not serialize inputs that have been disabled, so I made them readonly instead. Outcome checker will now total them properly.
=> Quiz type test outcome fix

elements/clickhole-medal-tracker/clickhole-medal-tracker.scss, elements/clickhole-medal-tracker/components/medal.js
Hey @daytonn, I added a few flexbox styles that should take care of the vertical alignment of the medal numbers and contender names. These were styles I had written to override it in the clickhole project, and they definitely belong here instead.
=> Medal tracker styles

elements/bulbs-video/bulbs-video-examples.js, elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js, elements/bulbs-video/elements/rail-player/components/root.js, elements/bulbs-video/elements/rail-player/components/root.test.js, elements/bulbs-video/rail-player-examples.js, examples/fixtures/bulbs-video/vtt-captioning.json, examples/fixtures/rail-player/with-captioning.json
@collin @daytonn @kand @MelizzaP.  For Monday review, this PR will enable closed captioning on our video player as an option if it finds a `text/vtt` closed caption track in the list of sources.  It will also make it so the default option of whether to display them is enabled for the rail-player.  Also, docs for reference to JWPlayer are here (https://support.jwplayer.com/customer/portal/articles/1407438-adding-closed-captions)
Test link with an example here: 
http://closed-captioning.test.onionstudios.com/videos/watch-coach-speedman-make-a-difference-in-the-life-of-a-young-middle-manager-4257
You'll need to enable via the `CC` hover in the video player controls
=> Enabling VTT Captions and making them the default for the rail player

elements/share-tools/components/share-tool.js, elements/share-tools/components/share-tool.test.js, elements/share-tools/components/via-twitter.js, elements/share-tools/components/via-twitter.test.js
Hey cool-crew.
Proposal for the twitter share tools. This adds some defaults for 
````html
<share-via-twitter>
```
In the absence of a `twitter-handle` attribute, this will check the page for a `twitter:site` meta tag.
```html
<meta name="twitter:site" content="@TheOnion">
```
A `twitter-handle` defined directly on a `<share-via-twitter>` will take precedence.
And similarly for the `share-title` attribute of `<share-tools>`. Now `<share-via-twitter>` and `<share-via-email>` will look for an og:title and use that as a default.
```html
<meta name="og:title" content="‘I Can’t Do This Anymore,’ Think 320 Million Americans Quietly Going About Day">
```
=> update twitter share tools to read from on-page meta tags

elements/share-tools/components/via-twitter.test.js, lib/bulbs-elements/util/in-view-monitor.js, lib/bulbs-elements/util/in-view-monitor.test.js, lib/bulbs-elements/util/index.js, lib/bulbs-elements/util/load-on-demand.test.js
This utility allows an element to opt into two new events:
`enterviewport`
`exitviewport`
It can be handily used in the lifecycle hooks of an element.
```js
import { InViewMonitor } from 'bulbs-elements/status';
class RealCoolElement extends BulbsHTMLElement {
attachedCallback () {
InViewMonitor.add(this);
}
detachedCallback () {
InViewMonitor.remove(this);
}
}
registerElement('real-cool-element', RealCoolElement);
let coolElement = document.create('real-cool-element');
coolElement.addEventListener('enterviewport', function () {});
coolElement.addEventListener('exitviewport', function () {});
```
This will be used in the `<video is="bulbs-cinemagraph">` to play/pause it when it enters/leaves the viewport.
@kand @daytonn
=> a utility that monitors when items enter/exit view

elements/bulbs-cinemagraph/README.md, elements/bulbs-cinemagraph/bulbs-cinemagraph-examples.js, elements/bulbs-cinemagraph/bulbs-cinemagraph.js, elements/bulbs-cinemagraph/bulbs-cinemagraph.scss, elements/bulbs-cinemagraph/bulbs-cinemagraph.test.js, elements/share-tools/components/via-twitter.test.js, lib/bulbs-elements/util/in-view-monitor.js, package.json
Usage: This custom element uses the element extension form of custom elements.
So far we've been using fully custom elements.
Stuff like:
```html
<cool-custom-element></cool-custom-element>
```
and
```js
document.createElement('cool-custom-element');
```
But you can also extend built-in elements, like this:
```html
<video is="cool-video-extensions"></video>
```
and
```js
document.createElement('video', 'cool-video-exensions');
```
======
Here is how we can do cinemagraphs (that play inline on ios!!!)
with src attr:
```html
<video src="/video.mp4" is="bulbs-cinemagraph" cinemagraph-duration="1.55"/>
```
with source element:
```html
<video is="bulbs-cinemagraph" cinemagraph-duration="1.55">
<source src="/video.mp4"/>
</video>
```
Duration needs to be figured out and set by hand to prevent …
=> a <video is="bulbs-cinemagraph"> is born

webpack.base.js
Manually collect common chunks.
@daytonn @spra85 @daytonn @mparent61 
We had a major regression in our webpack builds.
I thought I had verified the commons chunk plugin as working. But currently all shared scripts are being compiled into every element.
`bulbs-poll`, `bulbs-video`, `share-tools`, etc. all include common assets, this is ballooning each script by quite a lot.
This also appears to be the cause of development environments crashing on page load. This is not the root cause, but serving so many large files in development seems to trigger it. In development mode this adds ~800K to each bulbs-element (sourcemaps, etc.).
=> Fix commons size

README.md, elements/campaign-product-shot/campaign-product-shot.js, elements/campaign-product-shot/campaign-product-shot.test.js
Wraps product shot image in a clickthrough url link.
**Release Type**: _patch_
No breaking changes, no major features.
**New**
1. `campaign-product-shot` element is now aware of a campaign's `clickthrough_url` and will use it to render a wrapping anchor tag.
=> Product shot clickthrough

elements/bulbs-carousel/bulbs-carousel.js, elements/bulbs-carousel/bulbs-carousel.test.js
The <bulbs-carousel> is initialized twice when the Load More button is clicked on special coverage landing pages (because it is recreated by a call to `innerHTML += '...'`.
This makes sure we don't create two carousel tracks when that happens
http://www.theonion.com/special/marketing click "Load More", scroll back up, and see the carousel items get really small.
http://carousel-track-fix.test.theonion.com/special/marketing click "Load More, scroll backup,  and see that the carousel items are not squashed.
=> don't lay the carousel track twice

elements/lazy-template/lazy-template-examples.js, elements/lazy-template/lazy-template.js, elements/lazy-template/lazy-template.scss, elements/lazy-template/lazy-template.test.js
@mparent61 If you link in bulbs-elements through your `docker-compose.yml` we'll be able to start testing out `<script is="lazy-template">`
=> <script is="lazy-template"> (ready for review)

elements/bulbs-carousel/bulbs-carousel.test.js, elements/bulbs-video/bulbs-video-examples.js, elements/bulbs-video/bulbs-video.js, elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js, elements/bulbs-video/components/root.js, elements/bulbs-video/elements/meta/components/root.js
@collin @daytonn @kand ... Queueing this up for a Monday review.
The purpose of the embedded attribute is to disable the JWPlayer advertising plugin for our own internal in-line article embedded players.
=> Added optional attribute for embedded; when enabled, the advertising plugin is disabled

elements/bulbs-video/elements/rail-player/rail-player.scss
Rail player button styling is causing a large unattached play button to float around in articles. The fix was to add a style to bulbs-elements styles 
Visit here (prod): http://www.avclub.com/article/fleabags-phoebe-waller-bridge-why-her-protagonists-242592
Scroll down until you will see a very large floating play button.
Visit here (test): http://elements-bump.test.avclub.com/article/fleabags-phoebe-waller-bridge-why-her-protagonists-242592
Scroll down and you will not see that giant play button
=> adjust rail player header styles

.babelrc, README.md, elements/bulbs-video/bulbs-video-examples.js, elements/bulbs-video/bulbs-video.js, elements/bulbs-video/bulbs-video.test.js, elements/bulbs-video/components/cover.js, elements/bulbs-video/components/cover.test.js, lib/bulbs-elements/util/load-on-demand.js, lib/bulbs-elements/util/load-on-demand.test.js, package.json
Implement [`loadOnDemand`](https://github.com/theonion/bulbs-elements/blob/374acbf897b46d6d3ed3d9b92aa80662101765ed/lib/bulbs-elements/util/load-on-demand.js) wrapper for `bulbs-video` to lazy load video elements.
**Release Type**: _patch_
No large-scale new features, updates should not be breaking.
**Updates**
1. `bulbs-video` now implements `loadOnDemand` for lazy loading. Lazy loading will occur by default. If this behavior is not necessary for a particular `bulbs-video`, give the element the `disable-lazy-loading` attribute to prevent lazy loading.
2. Stage 2 features for babel activated.
=> bulbs-video lazy loading

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js, elements/lazy-template/lazy-template.test.js
The share tools embeded in the jwplayer were linking to window.location.href as opposed to the video url
Added videohub reference id redirect to the jw player share tools
In the upper right hand corner of the homepage video player click the share icon and then the facebook or twitter icon. In production it should link link to the homepage, in test it should link to the video url
prod: http://www.theonion.com/
test: http://share-toolin.test.theonion.com
prod: http://www.avclub.com/
test: http://share-toolin.test.avclub.com
=> jw player embeded share tools

elements/bulbs-dfp/bulbs-dfp.js, elements/bulbs-dfp/bulbs-dfp.test.js, package.json
This PR:
Handles new events from `bulbs-public-ads-manager`
```js
this.addEventListener('dfpSlotRenderEnded', this.handleSlotRenderEnded);
this.addEventListener('dfpImpressionViewable', this.handleImpressionViewable);
this.addEventListener('dfpSlotOnload', this.handleSlotOnload);
```
And emits analytics events for them: 
```js
handleSlotRenderEnded () {
util.getAnalyticsManager().sendEvent({
eventCategory: 'bulbs-dfp-element Metrics',
eventAction: 'slotrenderended',
eventLabel: this.dataset.adUnit,
});
}
```
etc.
Also, this adds to the older analytics events we were sending around 30-second ad refreshing by sorting the events by `document.visibilityState`
```js
let browserVisibility = document.visibilityState;
/*....*/
eventAction: `30-second-refresh-candidate-${browserVisibility}`,
``` …
=> more detailed ads analytics

elements/bulbs-video/bulbs-video.js, elements/campaign-display/README.md, elements/campaign-display/campaign-display.js, elements/campaign-display/campaign-display.test.js, elements/campaign-display/components/campaign-display-root.js, elements/campaign-display/components/campaign-display-root.test.js
@collin @MelizzaP @kand @daytonn ... Looking for a review on this one.  The purpose of this is to add an optional attribute, `no-pixel` to the campaign-display element that will not add an ad to the DOM unless desired.  The intent is to use this for the slide out navigation on the sites, particularly The Onion.
=> Adding an optional attribute not to add a DFP pixel to the DOM

elements/bulbs-dfp/bulbs-dfp.js, elements/bulbs-dfp/bulbs-dfp.test.js
The first roll out of the 30 second ad refresh only delivered analytics events in place of actually reloading the ads.
In ~ a day or two we should have enough information to turn on the 30 second refresh with confidence. This PR will actually start reloading ads.
=> this PR reloads ads at 30s intervals

README.md, elements/bulbs-dfp/bulbs-dfp.js, elements/bulbs-dfp/bulbs-dfp.test.js
Move `refresh-interval` to ad unit configuration. Will be released in conjunction with https://github.com/theonion/bulbs-public-ads-manager/pull/17.
**Release Type**: _patch_
No large-scale new features or breaking changes. Current usages should fall back to default.
**New**
1. `bulbs-dfp` now reads `refreshInterval` from its ad unit configuration to get an amount of time until the ad should refresh. This will default to 30 seconds.
2. `bulbs-dfp` now reads `refreshDisabled` from its ad unit configuration to prevent the ad unit from refreshing.
**Updates**
1. `bulbs-dfp` no longer reads `refresh-interval` attribute.
=> bulbs-dfp refresh-interval optional

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js, lib/bulbs-elements/register.js
This fixes an issue where bulbs-video elements were still playing after they had been unmounted. An example can be viewed here: https://github.com/theonion/omni/pull/286
@collin @kand @MelizzaP
=> Unmount bulbs-video

lib/bulbs-elements/util/index.js, lib/bulbs-elements/util/on-ready-or-now.js, lib/bulbs-elements/util/on-ready-or-now.test.js
Another micro pr from american-voter.
Adds a utility event that calls a function when the document is ready, or right now if the document has already passed beyond the `loading` state.
=> on-ready-or-now

elements/bulbs-video/bulbs-video.js, elements/bulbs-video/bulbs-video.test.js, elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js, elements/bulbs-video/elements/video-carousel.js, elements/bulbs-video/elements/video-carousel.test.js, lib/bulbs-elements/util/on-ready-or-now.test.js
fixes a bug where there were two audio tracks playing at once
Also fixes an issue with the video carousel where it skipped ot the next clip when an ad finished, rather than when the video finished
Go to: http://www.avclub.com
Play an item in the video carousel. Wait for the ad to finish. The carousel will advance to the next video without playing the one you requested, and there will be multiple audio streams playing on top of each other.
Go to: http://fix-double-video.test.avclub.com
Play an item in the video carousel. Wait for the ad to finish. The content should start and only one audio track should play.
Scrub to almost the end of the video and wait for the video to complete. The next item in the carousel should start playing.
=> Fix double audio bug

elements/bulbs-dfp/bulbs-dfp.js, elements/bulbs-slideshow/bulbs-slideshow.test.js, elements/bulbs-video/bulbs-video.test.js, lib/bulbs-elements/util/in-view-monitor.js, lib/bulbs-elements/util/in-view-monitor.test.js
This change emits
`progresschange`
`pagestart`
`pageend`
events on elements that are tracked by the `InViewMonitor` utility.
This is used by the `<bulbs-page>` element to determine when to fire analytics events and alter the address bar with the pushstate api.
This duplicates part of the capabilities of the `<bulbs-reading-list>` and it would be wise to migrate the reading list to use `InViewMonitor` for these events. `InViewMonitor` batches calls to `getBoundingClientRect` which prevents inefficient 'layout thrashing'
=> In view page tracking

elements/bulbs-dfp/bulbs-dfp.test.js, karma.devicelab.js, lib/bulbs-elements/util/index.js, lib/bulbs-elements/util/lock-scroll.js, lib/bulbs-elements/util/lock-scroll.test.js, lib/bulbs-elements/util/scrolling-element.js, scripts/ci
This adds a utility that locks the scroll position to a given element.
`util.ScrollLock.lockToElement`
It stops locking scroll position when the user interacts with the browser, by scrolling, typing, touching, etc.
It adjust the scroll position on every animation frame, this mitigates the content-reflow that would otherwise bump the scroll position.
@kand @MelizzaP @spra85
=> Tests for scroll locking

elements/bulbs-video/elements/rail-player/rail-player.js
Rail player is no longer auto playing videos. Adding this back in. 
@collin @spra85 
Example here:
https://github.com/theonion/omni/pull/365
=> Make rail player auto play videos

elements/bulbs-dfp/bulbs-dfp.js, elements/bulbs-dfp/bulbs-dfp.test.js
This PR removes a lot of the event tracking noise that pushed us over our GA monthly hit allotment last month.  Preserves an event only for when an ad refresh is triggered.
Test link: 
http://less-event-noise.test.theonion.com/
=> Removing a lot of the event chatter to measure refresh/viewport check

elements/bulbs-dfp/bulbs-dfp.js, elements/bulbs-dfp/bulbs-dfp.test.js, elements/bulbs-video/elements/rail-player/rail-player.test.js, elements/campaign-display/campaign-display.js
This change is coupled with the updates to the ads manager here (https://github.com/theonion/bulbs-public-ads-manager/pull/20) and makes the call to refresh the ad slot using the new method exposed by the ads manager PR.
Test link below (http://lazy-load-ads.test.clickhole.com), items for regression test: 
- Homepage ads
- Campaign pixels
- Article ads
- `inread` ads in article body
=> Lazy load ads

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js
@spra85 @MelizzaP @kand 
There was a regression where this ref was lost.
=> restore the ref on the video container

elements/bulbs-video/elements/meta/components/root.js, elements/bulbs-video/elements/meta/components/root.test.js, elements/bulbs-video/elements/meta/meta.js
This is a compromise to get us around a sticky situation. Our properties don't have full video data at time of page render.  This leads us to do quite a bit of json fetching from onionstudios to complete that data on the front end.
The video json data has a series url that points to onionstudios.com.
Now our properties are starting to host their own series pages. But that url isn't available in the video meta element.
We're letting the property define the url prefix that is to be mashed together with the series slug.
@kand @spra85 (@mparent61 getting you in here because we discussed this previously)
This will be used as:
```html
<bulbs-video-meta relative-series-link-prefix="/series">
```
=> allow for a series url prefix in the video meta

elements/campaign-display/components/campaign-display-root.js, elements/campaign-display/components/campaign-display-root.test.js
Make sure we do not make an ad request for the campaign-pixel if the campaign is inactive
Test link: 
http://no-inactive-dfp-pixel.test.theonion.com/interactive/guide-to-extraterrestrial-life
=> Do not request campaign-pixel ad slot if the campaign is inactive

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js, elements/bulbs-video/elements/video-carousel.js, elements/bulbs-video/elements/video-carousel.test.js
This styles the first item in the carousel properly on first video play.
**Release Type**: _patch_
No major features, only a fix.
=> style first carousel item properly on first play

elements/bulbs-flyover-menu/bulbs-flyover-menu.js
Hot potato fix here. Currently bulbs-flyover is closing when menu is selected. We removed this when we launched resp header but somehow made it back.  We are transferring the close action to the button element
@collin @MelizzaP @kand @spra85
=> Do not auto close bulbs-flyout when menu is selected

elements/bulbs-clickventure/clickventure.js
clickventures initiate a scroll event on load that interferes with infinite scroll, for example if a user is on an article and the 2nd or 3rd content item in the reading list is a clickventure. Once the clickventure loads in the user will be scrolled to the clickventure. 
Clickventures will not trigger scroll behavior unless clickventure is in the veiwport
link: http://clickventure-fix.test.clickhole.com/clickventure/want-leave-earth-go-colonize-mars-5118
There will be multiple clickventures in the reading list, and there should be no odd scrolling or jumping behavior
=> clickventures must be in viewport to trigger scroll action

elements/bulbs-reading-list/lib/reading-list-article.js
Working on getting audience exchange (Taboola) set up on ClickHole via adding it to `bulbs-reading-list`. It's similar to what is [currently](https://github.com/theonion/omni/blob/master/onion/onion/static/javascript/article-list-init.js#L35) set up on Onion.
Currently having a fun time figuring out why it works locally and not on test: http://ch-reading-list-i2.test.clickhole.com/article/spellbinding-we-asked-nature-photographers-describ-5261
=> Taboola on reading list

elements/bulbs-video/fields/video-request.js
Reverts theonion/bulbs-elements#228
Need to make `credentials` optional, test needs a value, production does not.
=> Revert "include credentials in request for video"

elements/bulbs-video/bulbs-video.js
In special coverage carousels, coming in on a sub-url would play two videos at once.
This changes the timing of the URL swap and only one video plays:
www.theonion.com/special/gaming/video/5117
http://sc-video-carousel-bug.test.theonion.com/special/gaming/video/5117
=> Fixes a bug where multiple videos would play at once

elements/bulbs-pinned-element/bulbs-pinned-element.js, elements/bulbs-pinned-element/bulbs-pinned-element.test.js
There were some edge cases around scrolling above/below the pinned element container.
_Breaks if you command+up/command+down rapidly:_
http://staff.clickhole.com/article/social-media-fail-long-john-silvers-just-posted-vi-5388
_should scroll better:_
http://pinned-element-fix.test.clickhole.com/article/social-media-fail-long-john-silvers-just-posted-vi-5388
=> Pinned element fix

elements/bulbs-slick-slideshow/bulbs-slick-slideshow.js, elements/bulbs-slick-slideshow/bulbs-slick-slideshow.test.js, package.json
cleaner commit than https://github.com/theonion/bulbs-elements/pull/241, didn't want to rebase
two things here:
- 1. more precise selector (fixes reading list initialization issue for subsequent slideshows)
- 2. isolate key events (current bug on prod - left/right controls slideshows outside of viewport, this prevents that)
=> bulbs slideshow followup v2

elements/bulbs-reading-list/components/bulbs-reading-list-menu-item-clickable-area.js, elements/bulbs-reading-list/lib/reading-list-menu-item.js, elements/bulbs-reading-list/lib/reading-list-menu-item.test.js
Allows a more limited clickable area in a reading list menu item, addresses the issue where we want the feature type and campaign to be clickable for their own URLs apart from scrolling to a reading list article.
=> allow a more specific clickable area in reading list menus

elements/bulbs-article-body/bulbs-article-body.js, elements/bulbs-article-body/bulbs-article-body.test.js
This was passing the result of `querySelectorAll` into `iFrameResize` which caused a type error. Now it calls iFrameResize with each iframe individually.
I believe I had tested against a different version of iFrameResize / got confused by test branch deployment failures.
=> call iFrameResize with each iframe

elements/bulbs-reading-list/lib/reading-list-article.js, elements/bulbs-reading-list/lib/reading-list-article.test.js, elements/bulbs-reading-list/lib/reading-list-articles.test.js
Will be released together with the changes in https://github.com/theonion/omni/pull/870. Renames `GA_` variable prefixes to `GOOGLE_ANALYTICS_` for clarity.
Will break existing functionality if sites references to these variables are not renamed.
=> GA_ID to GOOGLE_ANALYTICS_ID

elements/bulbs-video/elements/video-carousel.js, elements/bulbs-video/elements/video-carousel.test.js
looks like this was autoplaying first video regardless of the second video that is selected. can revisit afterward for followup fix, this (should) just disable annoying audio.
corresponding omni pr: https://github.com/theonion/omni/pull/899
=> removing event listener for now

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js
This PR simply adjusts the ad unit size that maps to standard preroll in the ad server.  It was previously 400x300 and should have been 640x480 all along.
Test links are reflected in the omni PR: https://github.com/theonion/omni/pull/943
This would be a `patch` release.
=> Updating preroll ad unit size

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js
This simply adds a new possible value for the`type` custom param key/value, to pass in a blanket `sponsored` type in instances where a stand-alone video might be sponsored (defined herein as the presence of the `targetCampaignId`).  It will make it easier to globally exclude any sponsored video from affected line items on the ops side.
Will be a `minor` release.
=> Add a new value for type to be used for possible preroll exclusion

elements/bulbs-reading-list/lib/reading-list-article.js
this will eventually be fully refactored but in order to prevent numerous analytics events from firing, made use of `InViewMonitor` similar to the implementation in `bulbs-page` and the utilility @collin made here https://github.com/theonion/bulbs-elements/pull/267
This change should fix the behavior on all 3 properties
[Avclub](http://avc-refresh-article-scroll.test.avclub.com/article/career-suicide-thrashes-back-life-tighten-screws-249512)
[onion](http://update-analytics.test.theonion.com)
[clickhole](http://update-analytics.test.clickhole.com)
=> update analytics using `InViewMonitor` events 

lib/bulbs-elements/util/in-view-monitor.js, lib/bulbs-elements/util/in-view-monitor.test.js
This PR will be used in a subsequent change to allow `reading-list-article` to listen to its own `inview-rect` events and trigger the page start logic to match the old way using the pixel positioning of itself.
=> Added new inview-rect event so event listeners can use that info how they choose

elements/bulbs-page/bulbs-page.js, elements/bulbs-video/components/revealed.test.js
Fix for json parsing error when content analytics aren't defined on `bulbs-page` element.
Only a fix.
=> bulbs-page default for content analytics dimensions

elements/bulbs-page/bulbs-page.js, elements/bulbs-page/bulbs-page.test.js
Prevent `scroll_view` events unless the url has changed.
=> prevent tracking stuff if url has not changed

elements/bulbs-video/elements/video-carousel.js, elements/bulbs-video/elements/video-carousel.test.js
Undoes changes in #259 to allow first item to be highlighted on first play. Note, the underlying issue in #259 where two videos would play at the same time should be fixed by the hack in #285.
No breaking changes, only fixes.
1. Adds back functionality that selects first carousel item when playing the first video for the first time.
2. Fixes an issue where selecting an item other than the first as the first play switches the carousel back to the first item and plays that.
=> highlight first carousel item on first video play

elements/bulbs-video/bulbs-video.js, elements/bulbs-video/bulbs-video.test.js, lib/bulbs-elements/register.js
Fixes register functionality for stateless components. Allows the carousel to play the first video when  clicking on the first carousel item before clicking on any other carousel item.
Small patches for existing issues.
1. `registerReactElement` now keeps a flag separate of the `reactInstance` variable to determine if a component has rendered at least once. This allows the `attributeChanged` callback to treat stateful and stateless components the same way.
2. `bulbs-video` is now sensitive to updates to the `autoplay` attribute.
=> fix internals of stateless components, bulbs-video autoplay

elements/bulbs-nav/bulbs-nav.js, elements/bulbs-nav/bulbs-nav.test.js
`bulbs-nav` is stopping event propagation which was messing with click tracking events on avclub. This pr adds click tracking.
link: http://avc-mobile-nav.test.avclub.com
open the javascript console and type this command `window.analyticsTest = true` then click on the nav and you should see events firing for the nav
=> add analytics to nav

elements/bulbs-nav/bulbs-nav.js, package.json
This adds a feature to the avclub mobile nav. When a menu item is toggled `open` that element is then pushed to the top of the screen.
open  http://nav-scroll-test.test.avclub.com in a mobile environment. Any element that is toggled open should snap to the top of the screen.
=> `bulbs-nav` ScrollTop

elements/campaign-display/campaign-display.js, lib/bulbs-elements/util/load-on-demand.js, lib/bulbs-elements/util/load-on-demand.test.js
This PR does the following:
- Made campaign-display use `loadOnDemand`, e.g. lazy loaded
- Makes sure `loadOnDemand` does not load hidden elements even if they are "in the view port"
- Provides an external event (`bulbs-load`) to trigger evaluation of loading elements in addition to `scroll` and `resize`
Note, that the `isVisible` check in this PR is shamelessly borrowed from jQuery's [implementation](https://github.com/jquery/jquery/blob/master/src/css/hiddenVisibleSelectors.js#L12) of it.
=> loadOnDemand improvements

elements/bulbs-pdfobject/bulbs-pdfobject-examples.js, elements/bulbs-pdfobject/bulbs-pdfobject.js
Will need to revisit to make `data-track-category` dynamic. But it is outside the scope of the request for Trump Docs GA events.  Since the PDFs have already been ingested in the CMS it would require updating all 80+ entries by passing the value in through the element. The end result of this work is it gives us some sort of metric with actual user interactions with the PDF. @theonion/front-end
=> Add some GA values to pdf-object fallback

elements/bulbs-reading-list/components/bulbs-reading-list-item.js, elements/bulbs-reading-list/components/bulbs-reading-list-item.test.js, elements/bulbs-video/elements/meta/components/root.test.js
@spra85 this looks like it's working! @theonion/front-end 
**Background**
Twitter embeds on articles that come after first one in the newswire reading list were not loading properly (they were just sitting there in blockquotes)
**Fix**
Added a twitter widget load (https://dev.twitter.com/web/javascript/initialization) into bulbs-reading-list-item.js to activate when the new article is loaded.
**Test Link**
http://twitter-embed.test.avclub.com/
It's tricky to test bc you have to get to an article with an embedded tweet in the newswire reading list (not the first article, those were working fine).. it's probably easiest to just embed a tweet into whatever article is second when you look at it (I'm not sure if the database will update overnight?)
=> Twitter embed readinglist

elements/bulbs-video/player-skin-overrides.scss
was bothering me - meant to get around to fixing this a while back but got caught up in kinja stuff.
before:
now:
omni pr: https://github.com/theonion/omni/pull/1231
http://video-player-vol-fix.test.avclub.com/video/legendary-wwe-announcer-jim-ross-reflects-great-mo-255801
=> minor video css tweaks

elements/bulbs-video/components/revealed.js, elements/bulbs-video/components/revealed.test.js
Kinja is passing through `exp_variation` into some of the iframe embeds, and we need to pass it through to the VAST call.
=> Tack exp_variation onto the VAST URL call if it is present in the URL

elements/bulbs-clickventure/bulbs-clickventure.js, elements/bulbs-clickventure/clickventure.js, elements/bulbs-quiz/bulbs-quiz.js, elements/bulbs-quiz/cosmode-quiz.js, elements/bulbs-quiz/multiple-choice-quiz.js, elements/bulbs-quiz/tally-quiz.js, elements/bulbs-quiz/test-quiz.js, elements/bulbs-video/components/revealed.test.js, lib/bulbs-elements/util/resize-parent-frame.js
Fix a few issues resizing Kinja CV and Quiz embeds:
- Resize quizzes on completion
- Resize Clickventures on node change 
- resizeParentFrame() now triggers additional re-sizes messages after timeouts, to allow images to load
- prevent misc `picturefill()` errors on embeds
- Fix misc unrelated Lint error in `revealed.test.js`
[Embedded Quiz](https://mparent61.kinja.com/test-embed-auto-sizing-1823657233)
[Embedded Clickventure](https://mparent61.kinja.com/clickventure-embed-auto-sizing-1823732820)
[Site Quizzes Still Work](http://bulbs-resize-fixes.test.clickhole.com/r/236)
[Site Clickventures Still Work](http://bulbs-resize-fixes.test.clickhole.com/r/1828)
=> Embed Auto-resizing fixes

package.json, webpack.base.js
This should fix the ./scripts/tag-and-release script issues with upgraded Node version; also forces a Node engine version so it's clear what version of Node the script is known to work with.
=> Fix ./scripts/tag-and-release

elements/bulbs-clickventure/clickventure.js, elements/bulbs-quiz/multiple-choice-quiz.js, lib/bulbs-elements/util/in-iframe.js, lib/bulbs-elements/util/index.js, lib/bulbs-elements/util/resize-parent-frame.js
Similar fixes for buggy "is embedded" check (see https://github.com/theonion/omni/pull/1400).
(Mirrors what JW does too)
- Adds new `inIframe` utility method (https://stackoverflow.com/a/326076/8903106)
- Removes some embed checks around `window.picturefill()`, we'll just stub this out for embeds (much simpler way to avoid many `picturefill` JS errors).
=> Fix embed check

elements/bulbs-quiz/cosmode-quiz.js, elements/bulbs-quiz/multiple-choice-quiz.js, elements/bulbs-quiz/test-quiz.js
Was missing a `resizeParentFrame()` calls, which should match wherever we call `window.picturefill()`.  (Maybe there's a cleaner way to inject this call inside `window.picturefill()`, but this should cover all cases.)
Note how this "Test Quiz" embed now correctly expands whenever you click any answer.
https://mparent61.kinja.com/another-quiz-embed-1824001702
=> Quz embeds resize parent frame whenever they expand

elements/bulbs-clickventure/bulbs-clickventure.js, elements/bulbs-quiz/bulbs-quiz.js, elements/bulbs-quiz/cosmode-quiz.js, elements/bulbs-quiz/multiple-choice-quiz.js, elements/bulbs-quiz/tally-quiz.js, elements/bulbs-quiz/test-quiz.js
More auto-resizing fixes for Kinja embeds.
Triggers parent resize event on:
1. Quiz + Clickventure 'resize' window events (i.e. changing browser width)
1. Quiz input `change` events (i.e. checking answers)
1. Make screen narrow, notice how automatically re-sizes (and "Get Results" still visible)
2. Click on longer text answers to trigger re-flow to new line. Notice how re-sizes (and "Get Results" still visible)
https://mparent61.kinja.com/cosmo-quiz-wolverine-1824284821
1. Make screen narrow, notice how automatically re-sizes (and "Get Results" still visible)
https://mparent61.kinja.com/clickventure-1824111481
=> Fix more Clickhole embed resizing issues

elements/bulbs-splitpic/bulbs-splitpic-examples.js, elements/bulbs-splitpic/splitpic.js
The #load event in jquery was removed in jquery 3.x (http://api.jquery.com/load-event/), so this removes the usage of it in VerticalSplitPic
=> Fix for vertical splitpic using the #load event
